version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - intrange
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
    - prealloc
  settings:
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    funlen:
      lines: -1
      statements: 50
    gocritic:
      enabled-tags:
        - diagnostic
        - style
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - commentedOutCode
    errorlint:
      asserts: false
    lll:
      line-length: 140
    revive:
      severity: error
    staticcheck:
      checks:
        - all
        - -ST1005
  exclusions:
    presets:
      - comments
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - mnd
          - lll

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      rewrite-rules:
        - pattern: 'interface{}'
          replacement: 'any'
